/**
 * Stable error codes shared by the extension and the SDK.
 * Codes are part of the public contract: never rename, only add.
 */
export const ErrorCode = {
  NOT_INSTALLED: 'NOT_INSTALLED',
  NOT_CONNECTED: 'NOT_CONNECTED',
  EXTENSION_DISCONNECTED: 'EXTENSION_DISCONNECTED',
  TIMEOUT: 'TIMEOUT',
  ORIGIN_NOT_ALLOWED: 'ORIGIN_NOT_ALLOWED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  PAIRING_REJECTED: 'PAIRING_REJECTED',
  INVALID_REQUEST: 'INVALID_REQUEST',
  REPLAY_DETECTED: 'REPLAY_DETECTED',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_CAPABILITY: 'UNSUPPORTED_CAPABILITY',
  UNSUPPORTED_FORMAT: 'UNSUPPORTED_FORMAT',
  MAPPING_NOT_FOUND: 'MAPPING_NOT_FOUND',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  DEVICE_PERMISSION_REQUIRED: 'DEVICE_PERMISSION_REQUIRED',
  DEVICE_BUSY: 'DEVICE_BUSY',
  DEVICE_DISCONNECTED: 'DEVICE_DISCONNECTED',
  TRANSFER_FAILED: 'TRANSFER_FAILED',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  JOB_CANCELLED: 'JOB_CANCELLED',
  PRINT_WINDOW_CLOSED: 'PRINT_WINDOW_CLOSED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface SerializedError {
  code: ErrorCode;
  message: string;
  /** Machine readable, never contains document content. */
  details?: Record<string, unknown>;
}
